# Generated by Django 6.0.3 on 2026-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('durum', models.CharField(choices=[('calisiyor', 'Çalışıyor'), ('ariza', 'Arıza'), ('bakim', 'Bakımda')], default='calisiyor', max_length=20)),
                ('ariza_notu', models.TextField(blank=True, null=True)),
                ('son_bakim', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
