# Generated by Django 6.0.3 on 2026-03-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='robotlar/'),
        ),
    ]
