# Generated by Django 6.0.3 on 2026-03-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0002_robot_resim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_durum', models.CharField(max_length=20)),
                ('yeni_durum', models.CharField(max_length=20)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('notlar', models.TextField(blank=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='uretim.robot')),
            ],
        ),
    ]
