# Generated by Django 6.0.3 on 2026-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uretim', '0003_arizakaydi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('konu', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('okundu', models.BooleanField(default=False)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
